spring:
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: ERROR
    '[io.trutz]': INFO
management:
  endpoints:
    web:
      exposure:
        include: prometheus